name: Tests
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
# Ensures that only the latest commit is running for each PR at a time.
# Ignores this rule for push events.
concurrency:
  group: ${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true
jobs:
  unit-test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu, windows, macos ]
    env:
      GOPROXY: direct
      GRADLE_OPTS: -Dorg.gradle.daemon=false
      JFROG_CLI_LOG_LEVEL: "DEBUG"
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python3
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install pipenv & poetry
        run: python -m pip install pipenv poetry

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Install NuGet 6.x
        uses: nuget/setup-nuget@v2
        with:
          nuget-version: 6.x

      - name: Install dotnet 8.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Install pnpm 9.x
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Go with cache
        uses: jfrog/.github/actions/install-go-with-cache@main

      - name: Tests
        run: go test -v -race -cover ./...
